// Copyright 2026 Gert Nutterts
// SPDX-License-Identifier: Apache-2.0

// pairing/dubov/dubov.go
package dubov

import (
	"context"
	"errors"
	"fmt"
	"sort"

	"github.com/zyzniewski/chesspairing"
	"github.com/zyzniewski/chesspairing/pairing/swisslib"
)

// ErrTooFewPlayers is returned when there aren't enough active players.
var ErrTooFewPlayers = errors.New("dubov pairing requires at least 1 active player")

// ErrNoPairingPossible is returned when no valid pairing can be found.
var ErrNoPairingPossible = errors.New("no valid pairing exists for the remaining players")

// Pair generates pairings for the next round using the Dubov system (C.04.4.1).
//
// Algorithm:
//  1. Build PlayerState for all active players
//  2. Handle single-player edge case (bye only)
//  3. PAB bye selection via DubovByeSelector if odd count
//  4. Build score groups and brackets
//  5. Match each bracket using Dubov G1/G2 algorithm
//  6. Allocate colours per Art. 5
//  7. Board ordering and final assembly
func (p *Pairer) Pair(_ context.Context, state *chesspairing.TournamentState) (*chesspairing.PairingResult, error) {
	// Honour pre-assigned byes for the upcoming round.
	state, preAssignedByes := swisslib.FilterPreAssignedByes(state)

	// Build player states.
	players := swisslib.BuildPlayerStates(state)

	if len(players) == 0 {
		if len(preAssignedByes) > 0 {
			return &chesspairing.PairingResult{Byes: preAssignedByes}, nil
		}
		return nil, ErrTooFewPlayers
	}

	var notes []string

	// Handle single player.
	if len(players) == 1 {
		byes := append([]chesspairing.ByeEntry{}, preAssignedByes...)
		byes = append(byes, chesspairing.ByeEntry{PlayerID: players[0].ID, Type: chesspairing.ByePAB})
		return &chesspairing.PairingResult{
			Byes:  byes,
			Notes: []string{players[0].ID + " receives a bye (only active player)"},
		}, nil
	}

	isRound1 := state.CurrentRound == 1

	// Assign PAB if odd number of players.
	var byePlayer *swisslib.PlayerState
	activePlayers := make([]*swisslib.PlayerState, len(players))
	for i := range players {
		activePlayers[i] = &players[i]
	}

	if swisslib.NeedsBye(len(activePlayers)) {
		byeSelector := DubovByeSelector{}
		byePlayer = byeSelector.SelectBye(activePlayers)
		if byePlayer != nil {
			notes = append(notes, fmt.Sprintf("%s receives PAB (bye)", byePlayer.ID))
			var remaining []*swisslib.PlayerState
			for _, ap := range activePlayers {
				if ap.ID != byePlayer.ID {
					remaining = append(remaining, ap)
				}
			}
			activePlayers = remaining
		}
	}

	// Build player states slice for BuildScoreGroups.
	playerStates := make([]swisslib.PlayerState, len(activePlayers))
	for i, ap := range activePlayers {
		playerStates[i] = *ap
	}

	// Build score groups and brackets.
	scoreGroups := swisslib.BuildScoreGroups(playerStates)
	brackets := swisslib.BuildBrackets(scoreGroups)

	// Build player map and rating map.
	playerMap := make(map[string]*swisslib.PlayerState, len(activePlayers))
	for _, ap := range activePlayers {
		playerMap[ap.ID] = ap
	}
	ratings := BuildRatingMap(playerStates)

	// Build match context.
	mctx := &matchContext{
		ratings:         ratings,
		isRound1:        isRound1,
		forbidden:       buildForbiddenPairSet(p.opts.ForbiddenPairs),
		completedRounds: len(state.Rounds),
		playerMap:       playerMap,
	}

	// Process brackets top-down with upward collapse on failure.
	allPairs, pairingNotes := processBrackets(brackets, mctx)
	notes = append(notes, pairingNotes...)

	// Board ordering: sort by max player score desc, bracket score desc, min TPN asc.
	sortBoardOrder(allPairs)

	// Allocate colours and build final pairings.
	topSeedColor := parseTopSeedColor(p.opts.TopSeedColor)
	pairings := make([]chesspairing.GamePairing, len(allPairs))
	for i, pair := range allPairs {
		whiteID, blackID := AllocateColor(pair.white, pair.black, i+1, topSeedColor)
		pairings[i] = chesspairing.GamePairing{
			Board:   i + 1,
			WhiteID: whiteID,
			BlackID: blackID,
		}
	}

	// Build result.
	result := &chesspairing.PairingResult{
		Pairings: pairings,
		Notes:    notes,
	}

	if len(preAssignedByes) > 0 {
		result.Byes = append(result.Byes, preAssignedByes...)
	}

	if byePlayer != nil {
		result.Byes = append(result.Byes, chesspairing.ByeEntry{PlayerID: byePlayer.ID, Type: chesspairing.ByePAB})
	}

	result.Notes = append(result.Notes, "Pairings generated by Dubov Swiss system (C.04.4.1)")

	return result, nil
}

// parseTopSeedColor converts the TopSeedColor string option to a *swisslib.Color.
func parseTopSeedColor(opt *string) *swisslib.Color {
	if opt == nil || *opt == "auto" || *opt == "white" {
		return nil
	}
	if *opt == "black" {
		c := swisslib.ColorBlack
		return &c
	}
	return nil
}

// buildForbiddenPairSet converts the options ForbiddenPairs slice into
// the canonicalized map format used by criteria.
func buildForbiddenPairSet(pairs [][]string) map[[2]string]bool {
	if len(pairs) == 0 {
		return nil
	}
	m := make(map[[2]string]bool, len(pairs))
	for _, pair := range pairs {
		if len(pair) == 2 {
			m[swisslib.CanonicalPairKey(pair[0], pair[1])] = true
		}
	}
	return m
}

// sortBoardOrder sorts pairs for board assignment:
// 1. Max player score descending
// 2. Bracket score descending
// 3. Min TPN ascending
func sortBoardOrder(pairs []proposedPairing) {
	sort.SliceStable(pairs, func(i, j int) bool {
		maxI := pairs[i].white.Score
		if pairs[i].black.Score > maxI {
			maxI = pairs[i].black.Score
		}
		maxJ := pairs[j].white.Score
		if pairs[j].black.Score > maxJ {
			maxJ = pairs[j].black.Score
		}
		if maxI != maxJ {
			return maxI > maxJ
		}
		if pairs[i].bracketScore != pairs[j].bracketScore {
			return pairs[i].bracketScore > pairs[j].bracketScore
		}
		minI := pairs[i].white.TPN
		if pairs[i].black.TPN < minI {
			minI = pairs[i].black.TPN
		}
		minJ := pairs[j].white.TPN
		if pairs[j].black.TPN < minJ {
			minJ = pairs[j].black.TPN
		}
		return minI < minJ
	})
}

// processBrackets processes all brackets top-down, handling floaters by merging
// them into the next bracket. When the last bracket produces only floaters
// (0 pairs), it collapses upward into the previous bracket and retries.
func processBrackets(brackets []swisslib.Bracket, mctx *matchContext) ([]proposedPairing, []string) {
	// bracketState tracks per-bracket results so we can collapse upward on failure.
	type bracketState struct {
		bracket swisslib.Bracket
		result  *bracketResult
	}

	var notes []string
	states := make([]bracketState, 0, len(brackets))

	var pendingFloaters []*swisslib.PlayerState

	for i := 0; i < len(brackets); i++ {
		bracket := brackets[i]

		// Merge pending floaters into this bracket.
		if len(pendingFloaters) > 0 {
			bracket = swisslib.MergeIntoHeterogeneous(bracket, pendingFloaters)
			pendingFloaters = nil
		}

		result, _ := MatchBracketDubov(bracket, mctx)

		if len(result.floaters) > 0 && len(result.pairs) == 0 {
			// No pairs produced. If there's a next bracket, collapse into it.
			if i+1 < len(brackets) {
				brackets[i+1] = swisslib.CollapseBrackets(bracket, brackets[i+1])
				notes = append(notes, fmt.Sprintf("Collapsed brackets at score %.1f (forward)", bracket.OriginalScore))
				continue
			}

			// Last bracket with no pairs — try collapsing upward.
			if len(states) > 0 {
				// Undo the previous bracket's result and merge all its players with ours.
				prev := states[len(states)-1]
				states = states[:len(states)-1]

				// Collect all players from the previous bracket result and current floaters.
				var allPlayers []*swisslib.PlayerState
				for _, p := range prev.result.pairs {
					allPlayers = append(allPlayers, p.white, p.black)
				}
				allPlayers = append(allPlayers, prev.result.floaters...)
				allPlayers = append(allPlayers, result.floaters...)

				// Build a merged bracket and retry.
				merged := swisslib.Bracket{
					Players:       allPlayers,
					Homogeneous:   false,
					OriginalScore: prev.bracket.OriginalScore,
				}

				mergedResult, _ := MatchBracketDubov(merged, mctx)
				states = append(states, bracketState{bracket: merged, result: mergedResult})

				if len(mergedResult.floaters) > 0 {
					notes = append(notes, fmt.Sprintf("Collapsed brackets upward at score %.1f; %d players could not be paired",
						bracket.OriginalScore, len(mergedResult.floaters)))
				}
				continue
			}

			// Single bracket, no pairs possible.
			notes = append(notes, fmt.Sprintf("%d players could not be paired", len(result.floaters)))
			continue
		}

		states = append(states, bracketState{bracket: bracket, result: result})

		if len(result.floaters) > 0 {
			if i+1 < len(brackets) {
				pendingFloaters = result.floaters
			} else {
				notes = append(notes, fmt.Sprintf("%d players could not be paired", len(result.floaters)))
			}
		}
	}

	if len(pendingFloaters) > 0 {
		notes = append(notes, fmt.Sprintf("%d players could not be paired", len(pendingFloaters)))
	}

	// Collect all pairs from all bracket states.
	var allPairs []proposedPairing
	for _, s := range states {
		allPairs = append(allPairs, s.result.pairs...)
	}

	return allPairs, notes
}
